config/routes.rb
LogCarService::Application.routes.draw do
  #get "service_records/index"
  root :to => 'service_records#index'

  resources :service_types

  resources :service_records
end

app/models/service_record.rb
class ServiceRecord < ActiveRecord::Base
  belongs_to :service_type

  validates :service_type_id, :presence => true
  validates :mileage, :presence => true, :numericality => true
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  has_many :service_record
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/service_records_controller.rb
class ServiceRecordsController < ApplicationController
  before_action :set_service_record, only: [:show, :edit, :update, :destroy]

  # GET /service_records
  # GET /service_records.json
  def index
    @service_records = ServiceRecord.all
  end

  # GET /service_records/1
  # GET /service_records/1.json
  def show
  end

  # GET /service_records/new
  def new
    @service_record = ServiceRecord.new
  end

  # GET /service_records/1/edit
  def edit
  end

  # POST /service_records
  # POST /service_records.json
  def create
    @service_record = ServiceRecord.new(service_record_params)

    respond_to do |format|
      if @service_record.save
        format.html { redirect_to @service_record, notice: 'Service record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service_record }
      else
        format.html { render action: 'new' }
        format.json { render json: @service_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_records/1
  # PATCH/PUT /service_records/1.json
  def update
    respond_to do |format|
      if @service_record.update(service_record_params)
        format.html { redirect_to @service_record, notice: 'Service record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_records/1
  # DELETE /service_records/1.json
  def destroy
    @service_record.destroy
    respond_to do |format|
      format.html { redirect_to service_records_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_record
      @service_record = ServiceRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_record_params
      params.require(:service_record).permit(:service_type_id, :mileage, :notes)
    end
end

app/controllers/service_types_controller.rb
class ServiceTypesController < ApplicationController
  before_action :set_service_type, only: [:show, :edit, :update, :destroy]

  # GET /service_types
  # GET /service_types.json
  def index
    @service_types = ServiceType.all
  end

  # GET /service_types/1
  # GET /service_types/1.json
  def show
  end

  # GET /service_types/new
  def new
    @service_type = ServiceType.new
  end

  # GET /service_types/1/edit
  def edit
  end

  # POST /service_types
  # POST /service_types.json
  def create
    @service_type = ServiceType.new(service_type_params)

    respond_to do |format|
      if @service_type.save
        format.html { redirect_to @service_type, notice: 'Service type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @service_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_types/1
  # PATCH/PUT /service_types/1.json
  def update
    respond_to do |format|
      if @service_type.update(service_type_params)
        format.html { redirect_to @service_type, notice: 'Service type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_types/1
  # DELETE /service_types/1.json
  def destroy
    @service_type.destroy
    respond_to do |format|
      format.html { redirect_to service_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_type
      @service_type = ServiceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_type_params
      params.require(:service_type).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_records_helper.rb
module ServiceRecordsHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LogCarService</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/service_records/_form.html.erb
<%= form_for(@service_record) do |f| %>
    <% if @service_record.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@service_record.errors.count, "error") %> prohibited this service_record from being
            saved:</h2>

          <ul>
            <% @service_record.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :service_type %>
      <br>
      <%= f.collection_select :service_type_id, ServiceType.all, :id, :name, :prompt_text => "Please select" %>
    </div>
    <div class="field">
      <%= f.label :mileage %>
      <br>
      <%= f.text_field :mileage %>
    </div>
    <div class="field">
      <%= f.label :notes %>
      <br>
      <%= f.text_area :notes %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/service_records/edit.html.erb
<h1>Editing service_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_record %> |
<%= link_to 'Back', service_records_path %>

app/views/service_records/index.html.erb
<h1>Listing service_records</h1>

<table>
  <thead>
    <tr>
      <th>Service type</th>
      <th>Mileage</th>
      <th>Notes</th>
      <th>Logged</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @service_records.each do |service_record| %>
      <tr>
        <td><%= service_record.service_type.name %></td>
        <td><%= number_with_delimiter service_record.mileage %></td>
        <td><%= service_record.notes %></td>
        <td><%= l service_record.created_at, :format => :short %></td>
        <td><%= link_to 'Show', service_record %></td>
        <td><%= link_to 'Edit', edit_service_record_path(service_record) %></td>
        <td><%= link_to 'Destroy', service_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service record', new_service_record_path %>

app/views/service_records/new.html.erb
<h1>New service_record</h1>

<%= render 'form' %>

<%= link_to 'Back', service_records_path %>

app/views/service_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Service type:</strong>
  <%= @service_record.service_type.name %>
</p>
<p>
  <strong>Mileage:</strong>
  <%= number_with_delimiter @service_record.mileage %>
</p>
<p>
  <strong>Notes:</strong>
  <%= @service_record.notes %>
</p>

<%= link_to 'Edit', edit_service_record_path(@service_record) %> |
<%= link_to 'Back', service_records_path %>

app/views/service_types/_form.html.erb
<%= form_for(@service_type) do |f| %>
  <% if @service_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service_type.errors.count, "error") %> prohibited this service_type from being saved:</h2>

      <ul>
      <% @service_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/service_types/edit.html.erb
<h1>Editing service_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_type %> |
<%= link_to 'Back', service_types_path %>

app/views/service_types/index.html.erb
<h1>Listing service_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @service_types.each do |service_type| %>
      <tr>
        <td><%= service_type.name %></td>
        <td><%= service_type.description %></td>
        <td><%= link_to 'Show', service_type %></td>
        <td><%= link_to 'Edit', edit_service_type_path(service_type) %></td>
        <td><%= link_to 'Destroy', service_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service type', new_service_type_path %>

app/views/service_types/new.html.erb
<h1>New service_type</h1>

<%= render 'form' %>

<%= link_to 'Back', service_types_path %>

app/views/service_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service_type.description %>
</p>

<%= link_to 'Edit', edit_service_type_path(@service_type) %> |
<%= link_to 'Back', service_types_path %>